2019_ADSD_C-sharp_Team08/Controllers/HomeController.cs
using _2019_ADSD_C_sharp_Team08.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2019_ADSD_C_sharp_Team08.Controllers
{
    public class HomeController : Controller
    {
        private API _api = new API();

        public ActionResult Index()
        {
            //Get a random joke from the api
            var Joke = JsonConvert.DeserializeObject<JokeModel>(_api.Get("food/jokes/random?apiKey="));

            //Get a random fact from the api
            var Trivia = JsonConvert.DeserializeObject<TriviaModel>(_api.Get("food/trivia/random?apiKey="));

            ViewBag.Joke = Joke.Text;
            ViewBag.Trivia = Trivia.Text;

            return View();
        }

        
        public ActionResult About()
        {

            return View();
        }


    }
}

2019_ADSD_C-sharp_Team08/Controllers/UserHasIngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _2019_ADSD_C_sharp_Team08.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace _2019_ADSD_C_sharp_Team08.Controllers
{
    [Authorize]
    public class UserHasIngredientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //get the Api class
        private API _api = new API();

        // GET: UserHasIngredients
        public async Task<ActionResult> Index()
        {
            //get user id
            string UserId = User.Identity.GetUserId().ToString();

            //get the ingredients from user
            var ingredients = from ii in db.UserHasIngredients
                     where
                     ii.userId == UserId
                     select ii;

            //make a tuple from ingredient model and userhasingredient 
            List<Tuple<IngredientModel, UserHasIngredient>> listIngredients = new List<Tuple<IngredientModel, UserHasIngredient>>();
            foreach  (UserHasIngredient ingredient in ingredients)
            {
                //search ingredient by id
                IngredientModel im = JsonConvert.DeserializeObject<IngredientModel>(_api.Get("/food/ingredients/"+ ingredient.ingredientId + "/information?apiKey="));
                
                //add ingredient information and user ingredient information to tuple
                listIngredients.Add(new Tuple <IngredientModel, UserHasIngredient>(im, ingredient ));
            }

            return View(listIngredients);
        }


        // GET: UserHasIngredients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserHasIngredients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UserHasIngredient userHasIngredient)
        {
            //add ingriedient id to userhasingredient
            var ingredient_id = Request.Form["ingredient_id"];
            userHasIngredient.ingredientId = Int32.Parse(ingredient_id);

            //add amount id to userhasingredient
            var amount = Request.Form["amount"];
            userHasIngredient.amount = double.Parse(amount);

            //add ingriedient unit to userhasingredient
            var unit = Request.Form["unit"];
            userHasIngredient.unit = unit;

            //add ingriedient user id to userhasingredient
            userHasIngredient.userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                db.UserHasIngredients.Add(userHasIngredient);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(userHasIngredient);
        }

        // GET: UserHasIngredients/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //find the record with id
            UserHasIngredient userHasIngredient = await db.UserHasIngredients.FindAsync(id);

            //if it is not empty
            if (userHasIngredient == null)
            {
                return HttpNotFound();
            }
            return View(userHasIngredient);
        }

        // POST: UserHasIngredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            UserHasIngredient userHasIngredient = await db.UserHasIngredients.FindAsync(id);
            db.UserHasIngredients.Remove(userHasIngredient);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

2019_ADSD_C-sharp_Team08/Views/Home/About.cshtml
@{
    ViewBag.Title = "About us, Team 8A";
}
    <div class="jumbotron mt-4">
        <h2>@ViewBag.Title.</h2>
    </div>
<p>Wij zijn team 8A. We zijn een hard werkend motiverend en goed samenwerkend team. 
    Soms gaat er wel is iets mis maar we pakken het altijd goed op en maken er het beste van.</p>


<div class="row ">
    <div  class="col-md-4 mt-4">
        <img class="img-thumbnail" src="~/App_Images/Sander.PNG" alt="Generic placeholder image">
        <h3>Sander Bootsman</h3>
        <p style="min-height:6vh;">Dit is Sander. Hij is een top programmeur en komt uit Zaandam. Hij werkt op zolder met goed bereik. En is goed in Deceit :(</p>
        <p><a class="btn btn-danger" href="#" role="button">sander.bootsman@windesheim.nl</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-md-4 mt-4">
        <img class="img-thumbnail" src="~/App_Images/Harm.PNG" alt="Generic placeholder image">
        <h3>Harm Hendrik ten Napel</h3>
        <p style="min-height:6vh;">Dit is Harm. Hij komt uit Urk. Dat zegt wel al genoeg denk k he :)</p>
        <p><a style="background-color:deeppink;" class="text-light btn" href="#" role="button">harm-hendrik.ten.napel@windesheim.nl</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-md-4 mt-4">
        <img class="img-thumbnail" src="~/App_Images/Stefan.PNG" alt="Generic placeholder image">
        <h3>Stefan Koelewijn</h3>
        <p style="min-height:6vh;">Dit is Stefan. Hij is een aanwinst voor elk team! 
        Als je hem een opdracht geeft begint hij meteen zelfs als je nog in een vergadering zit!</p>
        <p><a class="btn btn-primary text-light" role="button">stefan.koelewijn@windesheim.nl</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-md-4 mt-4">
        <img class="img-thumbnail" src="~/App_Images/Maud.PNG" alt="Generic placeholder image">
        <h3>Maud de Haas</h3>
        <p style="min-height:6vh;">Dit is Maud. Let's keep it at that.</pstyle="min-height:6vh;">
        <p><a style="background-color: #f1c41f;" class="btn text-light" role="button">maud.de.haas@windesheim.nl</a></p>
    </div><!-- /.col-lg-4 -->
</div>
<hr />
Jongens het was een top jaar! Veel samen beleeft en komen er allemaal slimmer uit!

2019_ADSD_C-sharp_Team08/Views/Home/Index.cshtml
@model _2019_ADSD_C_sharp_Team08.Models.JokeModel
@{
    ViewBag.Title = "Home Page";
    var joke = ViewData["Joke"];
    var trivia = ViewData["Trivia"];
}

<div class="jumbotron mt-4" style="background-color:#ff751a;">
    <h1 class="text-light">Welcome to Team 8A's FridgeApp</h1>
    <p class="lead text-light">@joke</p>
    <p><a href="@Url.Action("Index", "UserHasIngredients")" class="btn btn-lg bg-light">Go to fridge &raquo;</a></p>
</div>

<strong><h2>Did you know:</h2> <br /><h4>@trivia</h4></strong>