2019_ADSD_C-sharp_Team08/Models/UserHasIngredient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace _2019_ADSD_C_sharp_Team08.Models
{
    public class UserHasIngredient
    {
        [Key]
        public long userHasIngredientId { get; set; }

        // Foreign key 
        [Display(Name = "AspNetUsers")]
        public string userId { get; set; }

        [ForeignKey("userId")]
        public virtual ApplicationUser ApplicationUser { get; set; }

        public long ingredientId { get; set; }

        public double amount { get; set; }

        public string unit { get; set; }

    }
}

2019_ADSD_C-sharp_Team08/Controllers/RecipeController.cs
using _2019_ADSD_C_sharp_Team08.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _2019_ADSD_C_sharp_Team08.Controllers
{
    public class RecipeController : Controller
    {
        private API _api = new API();


        // GET: Recipe
        public ActionResult Index(string[] checkbox)
        {
            //If nothing was checked
            if(checkbox == null)
            {
                //go back to the index page
                return RedirectToAction("Index", "UserHasIngredients");
            }
            else
            {
                //if the checkbox doesnt send a value the value is on
                if(checkbox.Contains("on") == true)
                {
                    //go back to the indexpage
                    return RedirectToAction("Index", "UserHasIngredients");
                }
                //Array to string for api call
                string ingredients = string.Join(",+", checkbox);

                //get all recipes with checked ingredients
                var allRecipes = JsonConvert.DeserializeObject<List<RecipeByIngredientModel>>(_api.Get("recipes/findByIngredients?ingredients="+ ingredients + "&number=5&ranking=1&apiKey="));

                return View(allRecipes);
            }
            
        }

        // GET: Recipe/Details/5
        public ActionResult Details(int id)
        {
            //get recipe information with id
            RecipeInformationModel RecipeInformation = JsonConvert.DeserializeObject<RecipeInformationModel>(_api.Get("/recipes/"+id+"/information?includeNutrition=false&apiKey="));

            return View(RecipeInformation);
        }



    }
}

2019_ADSD_C-sharp_Team08/Controllers/UserHasIngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _2019_ADSD_C_sharp_Team08.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace _2019_ADSD_C_sharp_Team08.Controllers
{
    [Authorize]
    public class UserHasIngredientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //get the Api class
        private API _api = new API();

        // GET: UserHasIngredients
        public async Task<ActionResult> Index()
        {
            //get user id
            string UserId = User.Identity.GetUserId().ToString();

            //get the ingredients from user
            var ingredients = from ii in db.UserHasIngredients
                     where
                     ii.userId == UserId
                     select ii;

            //make a tuple from ingredient model and userhasingredient 
            List<Tuple<IngredientModel, UserHasIngredient>> listIngredients = new List<Tuple<IngredientModel, UserHasIngredient>>();
            foreach  (UserHasIngredient ingredient in ingredients)
            {
                //search ingredient by id
                IngredientModel im = JsonConvert.DeserializeObject<IngredientModel>(_api.Get("/food/ingredients/"+ ingredient.ingredientId + "/information?apiKey="));
                
                //add ingredient information and user ingredient information to tuple
                listIngredients.Add(new Tuple <IngredientModel, UserHasIngredient>(im, ingredient ));
            }

            return View(listIngredients);
        }


        // GET: UserHasIngredients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserHasIngredients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UserHasIngredient userHasIngredient)
        {
            //add ingriedient id to userhasingredient
            var ingredient_id = Request.Form["ingredient_id"];
            userHasIngredient.ingredientId = Int32.Parse(ingredient_id);

            //add amount id to userhasingredient
            var amount = Request.Form["amount"];
            userHasIngredient.amount = double.Parse(amount);

            //add ingriedient unit to userhasingredient
            var unit = Request.Form["unit"];
            userHasIngredient.unit = unit;

            //add ingriedient user id to userhasingredient
            userHasIngredient.userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                db.UserHasIngredients.Add(userHasIngredient);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(userHasIngredient);
        }

        // GET: UserHasIngredients/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //find the record with id
            UserHasIngredient userHasIngredient = await db.UserHasIngredients.FindAsync(id);

            //if it is not empty
            if (userHasIngredient == null)
            {
                return HttpNotFound();
            }
            return View(userHasIngredient);
        }

        // POST: UserHasIngredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            UserHasIngredient userHasIngredient = await db.UserHasIngredients.FindAsync(id);
            db.UserHasIngredients.Remove(userHasIngredient);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

2019_ADSD_C-sharp_Team08/Views/UserHasIngredients/Create.cshtml
@model _2019_ADSD_C_sharp_Team08.Models.UserHasIngredient

@{
    ViewBag.Title = "Create";
}


<h2>Add ingredients to your fridge:</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Type your ingredient</h4>
    <hr />
    <label for="ingredient">Ingredient:</label>
    <input class="form-control " required type="text" name="ingredient" id="ingredient" autocomplete="off">
    <div id="divautocomplete"></div>
    <input required type="text" name="ingredient_id" id="ingredient_id" autocomplete="off" style="display:none;"><br />
    <label for="amount">Amount:</label>
    <input class="form-control" required type="text" name="amount" id="amount" autocomplete="off"><br />
    <label for="amount">Select unit:</label>
    <select class="form-control" required name="unit" id="unit">
    </select>


        <div class="mt-2">
            <input style="background-color:#ff751a;" type="submit" value="Add" class="btn" />
        </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#ingredient').keyup(function () {
            var autocompleteText = $('#ingredient').val();
            if (autocompleteText.length > 2) {
                $.ajax({
                    url: "https://api.spoonacular.com/food/ingredients/autocomplete?number=3&metaInformation=true&query=" + autocompleteText + "&apiKey=b5edc92d105a42c986acc6bda72f6d60",
                    dataType: "json",
                    type: "GET",
                    contentType: "application/json;",
                    success: function (data) {
                        var val = '<ul id="userlist">';
                        var realArray = $.makeArray(data)
                        console.log(data);
                        $.map(realArray, function (value, key) {
                            val += '<li class="tt-suggestion" id="' + value.id + '">' + value.name + '</li>'
                            $('#unit').find('option').remove();
                            $.each(value.possibleUnits,function(key, value) 
                            {
                                $('#unit').append('<option value=' + value + '>' + value + '</option>');
                            });
                        })

                       
                        val += '</ul>'
                        $('#divautocomplete').show();
                        $('#divautocomplete').html(val);
                        $('#userlist li').click(function () {
                            $('#ingredient').val($(this).text());
                            $('#ingredient_id').val($(this).attr('id'));
                            $('#divautocomplete').hide();
                        })
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            }
         })
        
        $(document).mouseup(function (e) {
            var closediv = $("#divautocomplete");
            if (closediv.has(e.target).length == 0) {
                closediv.hide();
            }
        });
    
    });

</script>

2019_ADSD_C-sharp_Team08/Views/UserHasIngredients/Delete.cshtml
@model _2019_ADSD_C_sharp_Team08.Models.UserHasIngredient

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this ingredient?</h3>
<div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

2019_ADSD_C-sharp_Team08/Views/UserHasIngredients/Index.cshtml
@model List<Tuple<_2019_ADSD_C_sharp_Team08.Models.IngredientModel, _2019_ADSD_C_sharp_Team08.Models.UserHasIngredient>>

@{
    ViewBag.Title = "Refrigerator contents";
}

    <h2 class="mt-2">@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Add new items", "Create")
</p>

<ul class="list-group">
    <form action="@Url.Action("Index", "Recipe")" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()

        @foreach (Tuple<_2019_ADSD_C_sharp_Team08.Models.IngredientModel, _2019_ADSD_C_sharp_Team08.Models.UserHasIngredient> x in Model)
        {
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <input value="@x.Item1.Name" class="form-check-inline" type="checkbox" id="checkbox" name="checkbox[]">
                @x.Item1.Name
                @x.Item2.amount@x.Item2.unit
                @Html.ActionLink("Delete", "Delete", new { id = @x.Item2.userHasIngredientId })
            </li>
        }

        <div class="form-actions no-color">
            <input style="background-color:#ff751a;" type="submit" value="Search recipe" class="btn text-light mt-2" /> 
        </div>
    </form>
</ul>